# Generated by Django 4.2.7 on 2025-08-28 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="oidc_subject",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
